import random


def calculate_electricity(wind_speed_mph, number_of_turbines, duration):
    wind_speed_mps = wind_speed_mph * 0.44704  # convert mph -> m/s
    air_density = 1.225  # kg/m^3
    coefficient_of_power = random.uniform(0.4, 0.593)  # avg coefficient of power, which is a range based on EPA calculations
    # power generation formula:
    power = coefficient_of_power * air_density * pow(wind_speed_mps, 3) * number_of_turbines
    # coefficient of power * air density (kg/m^3) * wind speed ^3 (m/s) * number of turbines
    electricity = power * duration
    return power


def homes_powered(electricity):
    homes = electricity / 11000  # avg home uses 11000 kWh per year
    return homes


def main():
    wind_speed_mph = float(input("Enter the wind speed in miles per hour: "))
    number_of_turbines = int(input("Enter the number of turbines: "))
    duration = float(input("Enter the duration in hours: "))

    electricity = round(calculate_electricity(wind_speed_mph, number_of_turbines, duration), 3)
    homes = round(homes_powered(electricity), 3)
    co2_emissions_kg = round(electricity * 0.371, 3)  # avg kg of CO2 per kWh emitted
    co2_emissions_tons = round(co2_emissions_kg / 1000, 3)

    print(f"\nElectricity generated: {electricity} kWh")
    print(f"Homes powered: {homes}")
    print(f"CO2 emissions saved: {co2_emissions_kg} kg | {co2_emissions_tons} tons ")


if __name__ == '__main__': main()

# This program calculates the amount of electricity generated by wind turbines based on user input for wind speed and the number of turbines.
# It uses the calculate_electricity function to calculate the electricity generated.
# Then, it uses the homes_powered function to calculate the number of homes that can be powered by the electricity generated.
# Finally, it calculates and displays the CO2 emissions saved based on the electricity generated.


# POSSIBLE IMPROVEMENTS
# include the ability to enter a range of wind speeds or an average and recognizing what's been entered accordingly
# combine this with more Windmill data, land usage, precipitation in  a similar way to wind, turbine size and blade size
# eventually include a database of devices, machines, vehicles, equipment for emissions (potentially) and electricity needed to power them instead of just homes,
# allow the user to choose
# combine this program with graphs and wider functionality for the user to calculate other renewable energies and show potentially the non-renewable sources as well
# such as oil, natural gas, or maybe just a wider range of databases to pull from
